# Bench Marks and Tests for Code

In [1]:
import numpy as np
import time as t

In [2]:
def find_index_forloop(_values, _unsorted):
    N = len(_values)
    _idx = np.zeros(N, dtype=np.int32)
    for j in range(N):
        _idx[j] = np.argmax(_values[j] == _unsorted)
    return _idx

def find_index_1D_dict(_values, _dict):
    ''' Use a for loop and a dictionary. _values are the IDs to search for. _dict must be in format 
    (cell IDs: index) '''
    _idx_vec = np.zeros(len(_values), dtype=np.int32)
    for i in range(len(_values)):
        _idx_vec[i] = _dict[_values[i]]
    return _idx_vec

def find_index_1D_tile(_values, _unsorted):
    ''' tile and reshape the array '''
    # convert this to rows 
    _values_2d_T = np.atleast_2d(_values).transpose()
    _unsorted_2d = np.tile(_unsorted, (len(_values),1))
    _idx_vec = np.argmax(_values_2d_T == _unsorted_2d, axis=1)
    return _idx_vec

def find_index_1D_repeat(_values, _unsorted):
    ''' use repeat instead of tile '''
    # convert this to rows
    _values_2d_T = np.atleast_2d(_values).transpose()
    _unsorted_2d = np.repeat(np.atleast_2d(_unsorted), repeats=len(_values), axis=0)
    _idx_vec = np.argmax(_values_2d_T == _unsorted_2d, axis=1)
    return _idx_vec

In [3]:
a = np.arange(10)
np.random.shuffle(a)
vals = np.array([2,3])
print('Searching for: '+str(vals))
print('In: '+str(a))

Searching for: [2 3]
In: [7 0 9 5 4 8 2 6 1 3]


In [4]:
indices = find_index_1D_tile(vals, a)
print(indices)
indices = find_index_1D_repeat(vals, a)
print(indices)
indices = find_index_forloop(vals, a)
print(indices)

idx_dict = dict(zip(a, np.arange(10)))
indices = find_index_1D_dict(vals, idx_dict)
print(indices)

[6 9]
[6 9]
[6 9]
[6 9]


#### Big Loop for benchmarking

In [7]:
loop_num = 100
list_size = 250
tag_size = 25
time_list = []
label_list = ['tile', 'repeat', 'dict', 'for loop']

unsorted_nums = np.arange(list_size)
np.random.shuffle(unsorted_nums)
idx_dict = dict(zip(unsorted_nums, np.arange(list_size)))
tags = np.arange(tag_size)

## TILE ##
t0 = t.time()
for j in range(loop_num):
    indices = find_index_1D_tile(tags, unsorted_nums)
t1 = t.time()
time_list.append(t1 - t0)

## REPEAT ##
t0 = t.time()
for j in range(loop_num):
    indices = find_index_1D_repeat(tags, unsorted_nums)
t1 = t.time()
time_list.append(t1 - t0)

## DICT ##
t0 = t.time()
for j in range(loop_num):
    indices = find_index_1D_dict(tags, idx_dict)
t1 = t.time()
time_list.append(t1 - t0)

## forloop ##
t0 = t.time()
for j in range(loop_num):
    indices = find_index_forloop(tags, unsorted_nums)
t1 = t.time()
time_list.append(t1 - t0)

In [8]:
for m in range(len(time_list)):
    print(label_list[m]+':  '+str(np.round(time_list[m], 2)))

tile:  0.0
repeat:  0.0
dict:  0.0
for loop:  0.01


In [2]:
import numpy as np
my_array = None
if my_array is not None:
    print('yay')
my_array = np.array([1,2,3])
if my_array is not None:
    print('found it')

found it


In [3]:
A = np.arange(12).reshape((2,6))
print(A)
A[:,1:6] = 0
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[0 0 0 0 0 0]
 [6 0 0 0 0 0]]


In [4]:
track_sample_layer = np.array([1,2,3,12,13,14])

track_arr = np.zeros((6,6))
track_arr[:,5] = track_sample_layer
# track flag
track_arr[:,4] = np.ones((6,))
track_arr[:,3] = 5

# Fill in eta and phi values
# this is complicated - simplify?
p, q = 0, 1
for j in range(12):
    # This gives the key for the track dict
    track_arr[p,q] = 7
    if j%2 != 0:
        p += 1
        q = 1
    else:
        q = 2
print(track_arr)

[[ 0.  7.  7.  5.  1.  1.]
 [ 0.  7.  7.  5.  1.  2.]
 [ 0.  7.  7.  5.  1.  3.]
 [ 0.  7.  7.  5.  1. 12.]
 [ 0.  7.  7.  5.  1. 13.]
 [ 0.  7.  7.  5.  1. 14.]]


In [1]:
print((1008217/46) * 8)

175342.08695652173


In [8]:
C = track_arr[:,:6]
print(C)

[[ 0.  7.  7.  5.  1.  1.]
 [ 0.  7.  7.  5.  1.  2.]
 [ 0.  7.  7.  5.  1.  3.]
 [ 0.  7.  7.  5.  1. 12.]
 [ 0.  7.  7.  5.  1. 13.]
 [ 0.  7.  7.  5.  1. 14.]]


In [17]:
import time
import sys

toolbar_width = 40

# setup toolbar
sys.stdout.write("["+" "*toolbar_width+"]")
sys.stdout.flush()
time.sleep(1)
for j in range(toolbar_width):
    sys.stdout.write("\b")
sys.stdout.flush()

for i in range(toolbar_width):
    time.sleep(.1) # do real work here
    # update the bar
    sys.stdout.write("#")
    sys.stdout.flush()

sys.stdout.write("]\n") # this ends the progress bar

[                                       ########################################]


2

In [21]:
events = [i for i in range(10)]
print(events)
print(events[:1])
print(events[0])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0]
0


In [10]:
A = np.arange(6).reshape((2,3))
print(A)
B = np.array([0,1,0])
print(B)
print(A.shape)
print(B.shape)
print(np.dot(A,B))


[[0 1 2]
 [3 4 5]]
[0 1 0]
(2, 3)
(3,)
[1 4]


In [6]:
class callable_class:
    
    def __init__(self):
        self.a = 5
        self.b = 7
    
    def __call__(self, a, b):
        self.a = a
        self.b = b
        
class non_callable_class:
    
    def __init__(self):
        self.a = 5
        self.b = 7

In [7]:
call_obj = callable_class()
print(call_obj.a, call_obj.b)

call_obj(8,9)
print(call_obj.a, call_obj.b)

5 7
8 9


In [8]:
class non_callable_class:
    
    def __init__(self):
        self.a = 5
        self.b = 7

class return_class:
    
    def __init__(self):
        self.new_object = None
        self.build()
        
    def build(self):
        self.new_object = non_callable_class()
        return self.new_object

In [10]:
obj = return_class()
print(obj.new_object.a)

5
